CREATE TABLE PARTITION_METHODS_STORE (
  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PM_ID INT NOT NULL REFERENCES PARTITION_METHODS (PM_ID) ON DELETE CASCADE,
  TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  COL_NAME VARCHAR(256) NOT NULL,
  COL_INT BIGINT,
  COL_FLOAT DOUBLE,
  COL_TEXT VARCHAR(1024),
  COL_DATE DATE,
  COL_TIME TIME,
  COL_TIMESTAMP TIMESTAMP,
  COL_BOOL 	BOOLEAN,
  COMPOSITE_COL_COUNT INT NOT NULL
)
