CREATE TABLE PARTITION_METHODS (
  PM_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  TID INT NOT NULL REFERENCES TABLES (TID) ON DELETE CASCADE,
  PARTITION_TYPE VARCHAR(10) NOT NULL,
  PATH VARCHAR(1024),
  EXPRESSION VARCHAR(1024) NOT NULL,
  EXPRESSION_SCHEMA VARCHAR(1024) FOR BIT DATA NOT NULL,
  CONSTRAINT PARTITION_METHODS_PK PRIMARY KEY (PM_ID)
)