CREATE TABLE PARTITION_METHODS_STORE (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PM_ID INT NOT NULL,
  TID INT NOT NULL,
  COL_NAME VARCHAR(256) NOT NULL,
  COL_INT BIGINT,
  COL_FLOAT DOUBLE,
  COL_TEXT VARCHAR(1024),
  COL_DATE DATE,
  COL_TIME TIME,
  COL_TIMESTAMP TIMESTAMP,
  COL_BOOL TINYINT(1),
  COMPOSITE_COL_COUNT INT NOT NULL,
  FOREIGN KEY (PM_ID) REFERENCES PARTITION_METHODS (PM_ID) ON DELETE CASCADE
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
)
