CREATE TABLE PARTITION_METHODS (
  PM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TID INT NOT NULL,
  PARTITION_TYPE VARCHAR(10) NOT NULL,
  PATH VARCHAR(1024),
  EXPRESSION VARCHAR(1024) NOT NULL,
  EXPRESSION_SCHEMA VARCHAR(1024) NOT NULL,
  FOREIGN KEY (TID) REFERENCES TABLES (TID) ON DELETE CASCADE
)